name: Deploy Docker and Ec2
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  BuildContainer:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: matheusmaais
      IMAGE_NAME: hellownode
      IMAGE_TAG: main
    steps:
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.POC_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.POC_AWS_SECRET_KEY }}
      #     aws-region: us-east-1
      
      - name: Checkout Application
        uses: actions/checkout@v3

      - name: Build And Push Docker Image
        run: |
          docker build -t ${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG} .
          docker image push ${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG}